DIFF_GREAT_CELL = '$D$1'
DIFF_GOOD_CELL = '$G$1'
DIFF_BAD_CELL = '$J$1'
DIFF_VERY_BAD_CELL = '$M$1'

MISSED_GOOD_CELL = '$D$2'
MISSED_WARNING_CELL = '$G$2'
MISSED_BAD_CELL = '$J$2'

DIFFICIENT_DIFFERENCE_COL = '$T$1'
DIFFICIENT_DIFFERENCE_MISSED_COL = '$Y$1'
DIFFICIENT_MISSED_COL = '$Y$2'

DIFF_GREAT = 0.2
DIFF_GOOD = 0
DIFF_BAD = -0.1
DIFF_VERY_BAD = -0.2

MISSED_GOOD = 0.25
MISSED_WARNING = 0.5
MISSED_BAD = 0.75

DIFFICIENT_DIFFERENCE = 0.15
DIFFICIENT_DIFFERENCE_MISSED = 0
DIFFICIENT_MISSED = 1

DATA_START_ROW = 5
